import { Listing, Contact, ActivityEvent, AIAgent, WorkspaceSignal, DailyTask, DigitalIntentSignal } from './types.ts';

export const mockListings: Listing[] = [
  {
    id: "L-101",
    address: "1228 Willow Crest Lane",
    city: "Folsom",
    neighborhood: "Willow Creek",
    price: 949000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2850,
    lotSize: "0.25 acres",
    propertyType: "Single Family",
    status: "Active",
    daysOnMarket: 14,
    description: "Beautiful family home in Folsom.",
    sellerName: "Sarah Jenkins",
    keyFeatures: ["Remodeled Kitchen", "Backyard Entertaining Space", "Top Schools"],
    photoCategories: ["Exterior", "Kitchen", "Living Room", "Backyard"],
    photoGaps: ["Primary Bedroom (Too Dark)", "Entryway", "Pantry"],
    showingCount: 2,
    listingViews: 845,
    saves: 32,
    shares: 12,
    buyerDemandScore: 88,
    momentumScore: 65,
    sellerConfidenceRisk: 'Medium',
    marketingGapScore: 80,
    photoGapScore: 40,
    marketingStatus: "Active - Needs Refresh",
    recommendedNextAction: "Update listing copy to emphasize remodeled kitchen and schools. Create targeted email campaign for buyers under $950K.",
    imageUrl: "https://picsum.photos/seed/willow/600/400",
    aiInsight: "Getting strong photo engagement on kitchen/backyard, but showing conversion is low. Current price ($949K) may be slightly above the most active search range ($875K-$925K).",
    aiSummary: {
      working: "Strong awareness. Views and saves are healthy. Kitchen and backyard photos are driving engagement.",
      notWorking: "Showing requests are lower than expected. The $949K price point is slightly above the highest demand cluster.",
      likelyBuyer: "Young family looking for top Folsom schools and turnkey entertaining space.",
      missingMarketing: "Instagram carousel highlighting the backyard, targeted email to buyers searching under $950K.",
      matchedBuyers: ["Daniel Brooks", "Madison Clark"],
      sellerMessage: "Traffic is great, but buyers are hesitating to tour. We need to adjust the marketing copy to push the lifestyle and watch the $925K price band.",
      nextMoves: ["Refresh listing description", "Send targeted buyer email", "Create Instagram carousel", "Send seller update", "Invite Daniel Brooks and Madison Clark to private showing"]
    }
  },
  {
    id: "L-102",
    address: "4170 Ridgeview Court",
    city: "El Dorado Hills",
    neighborhood: "Ridgeview",
    price: 1350000,
    bedrooms: 5,
    bathrooms: 4.5,
    sqft: 4100,
    lotSize: "0.5 acres",
    propertyType: "Single Family",
    status: "Coming Soon",
    daysOnMarket: 0,
    description: "Luxury estate with panoramic views.",
    sellerName: "Trevor and Elise Morgan",
    keyFeatures: ["Pool", "Panoramic Views", "Wine Cellar"],
    photoCategories: ["Exterior", "Pool", "Kitchen", "Primary Suite"],
    photoGaps: ["Twilight Exterior", "Drone Shots"],
    showingCount: 0,
    listingViews: 120,
    saves: 15,
    shares: 5,
    buyerDemandScore: 95,
    momentumScore: 90,
    sellerConfidenceRisk: 'Low',
    marketingGapScore: 20,
    photoGapScore: 60,
    marketingStatus: "Pre-Launch",
    recommendedNextAction: "Create private launch campaign for top 7 matching buyers before public open house.",
    imageUrl: "https://picsum.photos/seed/ridgeview/600/400",
    aiInsight: "42 active buyers searching for similar homes. Strongest demand is $1.25M-$1.35M. 7 buyers saved similar homes in last 10 days.",
    aiSummary: {
      working: "Pre-market buzz is extremely high. 42 active buyers match this profile.",
      notWorking: "Missing twilight and drone photography which are critical for this price point.",
      likelyBuyer: "Luxury move-up buyer or Bay Area relocation seeking views and privacy.",
      missingMarketing: "Private showing invites, twilight hero image.",
      matchedBuyers: ["Olivia Stone"],
      sellerMessage: "Demand is surging before we even hit the market. We have 7 highly qualified buyers ready to tour.",
      nextMoves: ["Order twilight photos", "Send private launch invites", "Prep open house materials"]
    }
  },
  {
    id: "L-104",
    address: "2457 Blackstone Drive",
    city: "Granite Bay",
    neighborhood: "Blackstone",
    price: 2100000,
    bedrooms: 5,
    bathrooms: 5,
    sqft: 5200,
    lotSize: "1 acre",
    propertyType: "Single Family",
    status: "Active",
    daysOnMarket: 45,
    description: "Resort-style living in Granite Bay.",
    sellerName: "The Harrison Trust",
    keyFeatures: ["Resort Pool", "Guest House", "Gated"],
    photoCategories: ["All"],
    photoGaps: [],
    showingCount: 4,
    listingViews: 3200,
    saves: 85,
    shares: 40,
    buyerDemandScore: 65,
    momentumScore: 40,
    sellerConfidenceRisk: 'High',
    marketingGapScore: 90,
    photoGapScore: 10,
    marketingStatus: "Needs Push",
    recommendedNextAction: "Create Instagram carousel, email blast to luxury buyers, and private showing invite.",
    imageUrl: "https://picsum.photos/seed/blackstone/600/400",
    aiInsight: "Under-marketed on social media. Best campaign angle: luxury family living with resort-style outdoor space.",
    aiSummary: {
      working: "Photos are excellent. Property shows well online.",
      notWorking: "Momentum has stalled at 45 days. Social media presence is weak.",
      likelyBuyer: "High-net-worth family looking for multi-generational living (guest house).",
      missingMarketing: "Instagram carousel, luxury email blast, targeted Facebook ads.",
      matchedBuyers: ["Olivia Stone"],
      sellerMessage: "We need to inject fresh energy into the marketing. I'm launching a new digital campaign targeting Bay Area luxury buyers today.",
      nextMoves: ["Generate Instagram Carousel", "Draft Luxury Email Blast", "Call Seller"]
    }
  }
];

export const mockContacts: Contact[] = [
  {
    id: "C-101",
    name: "Daniel Brooks",
    type: "Buyer",
    budgetOrValue: "$900,000",
    preferredCities: ["Folsom", "El Dorado Hills"],
    timeline: "ASAP",
    leadSource: "Zillow",
    stage: "Warm Lead",
    assignedAgent: "Ava Ricker",
    lastContactedDate: "12 days ago",
    recentActivity: [
      "Viewed 1228 Willow Crest Lane 4 times in 48 hours",
      "Saved 3 Folsom listings",
      "Opened buyer email campaign"
    ],
    savedSearches: ["Folsom 3+ Bed < $950K"],
    viewedListings: ["L-101"],
    favoriteProperties: ["L-101"],
    notes: "Looking for a family home, concerned about interest rates.",
    relationshipStrength: "Medium",
    aiPriorityScore: 98,
    sentiment: 'Urgent',
    clientMemory: "Daniel is highly analytical. He watches days on market closely and is trying to time the interest rates. He loves Willow Creek but won't overpay.",
    recommendedNextAction: "Send personalized message asking if he wants to tour his top two saved homes this weekend.",
    suggestedMessage: "Hi Daniel, I noticed you've been keeping an eye on a few homes in Folsom, especially the one on Willow Crest. Would you like to set up a private tour this weekend before the open house?",
    revenuePotential: 'High',
    flagReason: "Viewed Folsom listing 4 times, saved 3 similar homes, no contact in 12 days",
    tags: ["Analytical", "Rate Sensitive"]
  },
  {
    id: "C-102",
    name: "Madison Clark",
    type: "Buyer",
    budgetOrValue: "$950,000",
    preferredCities: ["Folsom"],
    timeline: "Summer",
    leadSource: "Open House",
    stage: "Nurture",
    assignedAgent: "Ava Ricker",
    lastContactedDate: "5 days ago",
    recentActivity: ["Searched Empire Ranch neighborhood", "Adjusted saved search from $900K to $950K"],
    savedSearches: ["Folsom < $950K"],
    viewedListings: [],
    favoriteProperties: [],
    notes: "Wants Folsom, 3 bed min, likes backyards, nervous about rates, wants to wait until summer but keeps checking homes near Empire Ranch.",
    relationshipStrength: "Medium",
    aiPriorityScore: 85,
    sentiment: 'Anxious',
    clientMemory: "Madison is not just looking for a 3-bedroom home in Folsom. She repeatedly mentions backyards, Empire Ranch, and rate concerns. She needs reassurance around monthly payment and timing, not pressure.",
    recommendedNextAction: "Follow up Friday with 3 listings under $950K in Empire Ranch.",
    suggestedMessage: "Hi Madison, I found a few Folsom homes that match the backyard and 3-bedroom setup you mentioned. I also kept the price range in mind so we can stay realistic with monthly payment. Want me to send the strongest options?",
    revenuePotential: 'Medium',
    flagReason: "Increased budget on saved search overnight, showing increased readiness.",
    tags: ["Backyard Priority"]
  },
  {
    id: "C-103",
    name: "Trevor and Elise Morgan",
    type: "Seller",
    budgetOrValue: "$1,350,000",
    preferredCities: ["El Dorado Hills"],
    timeline: "Active Listing",
    leadSource: "Referral",
    stage: "Active Client",
    assignedAgent: "Ava Ricker",
    lastContactedDate: "9 days ago",
    recentActivity: ["Listing L-102 views increased 22%", "Opened seller update twice overnight"],
    savedSearches: [],
    viewedListings: [],
    favoriteProperties: [],
    notes: "Sellers of 4170 Ridgeview Court. Expect high communication.",
    relationshipStrength: "High",
    aiPriorityScore: 95,
    sentiment: 'Anxious',
    clientMemory: "Trevor is data-driven and wants to see the numbers. Elise cares more about how the home is presented. They get nervous if they don't hear from us weekly.",
    recommendedNextAction: "Send seller update. Listing has strong views but low showing conversion.",
    suggestedMessage: "Hi Trevor and Elise, quick update on Ridgeview: We saw a 22% increase in online views this week and 14 new saves. Buyers are noticing it. Showing requests are flat, so I recommend we refresh the listing copy to highlight the backyard and watch the $1.3M price band closely.",
    revenuePotential: 'High',
    flagReason: "Listing momentum is shifting and they haven't received an update in 9 days.",
    tags: ["High Communication"]
  },
  {
    id: "C-110",
    name: "Lauren Evans",
    type: "Buyer",
    budgetOrValue: "$1,200,000",
    preferredCities: ["Brooklyn"],
    timeline: "1 month",
    leadSource: "Open House",
    stage: "Hot Lead",
    assignedAgent: "Ava Ricker",
    lastContactedDate: "Today",
    recentActivity: ["Attended Open House at 36 Clinton", "Clicked listing brochure again overnight"],
    savedSearches: ["Clinton Hill Condos"],
    viewedListings: ["L-105"],
    favoriteProperties: ["L-105"],
    notes: "Asked about inspection timelines at the open house. Highly engaged.",
    relationshipStrength: "New",
    aiPriorityScore: 99,
    sentiment: 'Positive',
    clientMemory: "Lauren is a decisive buyer. She asked specific questions about inspection contingencies, meaning she is preparing to write an offer soon.",
    recommendedNextAction: "Follow up immediately regarding inspection questions.",
    suggestedMessage: "Hi Lauren, it was great meeting you today. Since you took a second look at the home online, I wanted to see if you had any follow-up questions on those inspection timelines or wanted to schedule a private showing?",
    revenuePotential: 'High',
    flagReason: "Re-engaged with open house materials 12 hours after attending.",
    tags: ["Decisive", "Open House Lead"]
  }
];

export const mockAgents: AIAgent[] = [
  { id: "A-1", name: "Next Best Action Agent", analyzing: "Cross-platform priority ranking", status: "Active", signalsReviewed: 1248, confidenceScore: 98, lastInsight: "Daniel Brooks is highest revenue probability today." },
  { id: "A-2", name: "Listing Momentum Agent", analyzing: "Views, saves, showings, market gaps", status: "Active", signalsReviewed: 312, confidenceScore: 91, lastInsight: "1228 Willow Crest Lane has strong views but weak showing conversion." },
  { id: "A-3", name: "Buyer Intent Agent", analyzing: "Search behavior, clicks, return visits", status: "Active", signalsReviewed: 845, confidenceScore: 94, lastInsight: "Madison Clark increased her budget filter to $950K." },
  { id: "A-4", name: "Client Memory Agent", analyzing: "Notes, emails, past transactions", status: "Idle", signalsReviewed: 56, confidenceScore: 99, lastInsight: "Updated preferences for Lauren Evans based on open house notes." },
  { id: "A-5", name: "Marketing Gap Agent", analyzing: "Asset coverage vs. buyer demographics", status: "Processing", signalsReviewed: 120, confidenceScore: 88, lastInsight: "Missing Instagram carousel for 2457 Blackstone Drive." },
  { id: "A-6", name: "Seller Confidence Agent", analyzing: "Communication frequency, listing stats", status: "Active", signalsReviewed: 45, confidenceScore: 95, lastInsight: "Trevor and Elise Morgan need an update; 9 days since last contact." },
  { id: "A-7", name: "Digital Intent Agent", analyzing: "Platform source attribution & intent signals", status: "Active", signalsReviewed: 2104, confidenceScore: 96, lastInsight: "1228 Willow Crest Lane is getting strong Zillow-style and Google Search traffic, but showing requests are not keeping pace." },
  { id: "A-8", name: "Notes-to-CRM Agent", analyzing: "Screenshots, text notes, call notes, open house notes", status: "Active", signalsReviewed: 87, confidenceScore: 97, lastInsight: "3 unstructured notes can be converted into CRM updates." }
];

export const mockWorkspaceSignals: WorkspaceSignal[] = [
  { id: "WS-1", platform: "Gmail", signal: "Seller asked about showing activity", aiMeaning: "Seller may be anxious", recommendedAction: "Draft seller update" },
  { id: "WS-2", platform: "Google Calendar", signal: "Showing with Madison tomorrow", aiMeaning: "Prep needed", recommendedAction: "Send confirmation & comps" },
  { id: "WS-3", platform: "Chrome", signal: "Ava opened Folsom market report", aiMeaning: "Listing appointment research", recommendedAction: "Build seller packet" },
  { id: "WS-4", platform: "Outlook", signal: "Buyer email has no reply for 48h", aiMeaning: "Follow-up gap", recommendedAction: "Draft text message" },
  { id: "WS-5", platform: "Teams", signal: "Meeting note mentioned price concern", aiMeaning: "Objection risk", recommendedAction: "Create pricing explanation" },
  { id: "WS-6", platform: "Excel", signal: "Open house list has 12 attendees", aiMeaning: "Follow-up needed", recommendedAction: "Rank leads & draft emails" },
  { id: "WS-7", platform: "Marketing Center", signal: "No flyer created for new listing", aiMeaning: "Marketing gap", recommendedAction: "Generate flyer" },
  { id: "WS-8", platform: "Buyer Demand", signal: "42 matching buyers for Ridgeview", aiMeaning: "Strong demand signal", recommendedAction: "Build buyer list" }
];

export const mockOvernightChanges = [
  "Daniel Brooks viewed 1228 Willow Crest Lane again at 9:42 PM.",
  "Madison Clark adjusted her saved search from $900K to $950K.",
  "Trevor and Elise opened their seller update twice.",
  "2457 Blackstone Drive had strong saves but no new showing requests.",
  "One open house lead from Sunday clicked the listing brochure again."
];

export const mockDailyTasks: DailyTask[] = [
  { id: "T-1", time: "9:00 AM", action: "Send Daniel Brooks private showing text.", completed: false },
  { id: "T-2", time: "9:20 AM", action: "Draft seller update for Trevor and Elise.", completed: false },
  { id: "T-3", time: "10:00 AM", action: "Create Instagram carousel for 1228 Willow Crest Lane.", completed: false },
  { id: "T-4", time: "11:00 AM", action: "Review Madison Clark's updated saved search.", completed: false },
  { id: "T-5", time: "1:00 PM", action: "Build listing appointment packet for Ridgeview Court.", completed: false },
  { id: "T-6", time: "3:00 PM", action: "Follow up with top 3 open house leads.", completed: false }
];

export const mockDigitalIntentSignals: DigitalIntentSignal[] = [
  {
    id: "DIS-1001",
    platform: "Listing Portal",
    listingId: "L-101",
    address: "1228 Willow Crest Lane",
    visitorType: "Anonymous",
    city: "Folsom",
    activity: "Viewed listing page",
    frequency: 312,
    source: "Zillow-style traffic",
    timestamp: "2026-05-20T09:42:00",
    intentScore: 78,
    aiInterpretation: "High awareness, but low showing conversion. Repeated anonymous activity suggests strong listing interest, but the lead has not converted yet.",
    recommendedAction: "Create stronger call-to-action and retarget interested buyers with a private showing invite."
  },
  {
    id: "DIS-1002",
    platform: "Email Campaign",
    listingId: "L-101",
    address: "1228 Willow Crest Lane",
    visitorType: "Known CRM Contact",
    knownContactId: "C-101",
    contactName: "Daniel Brooks",
    activity: "Clicked listing brochure twice",
    frequency: 2,
    source: "Targeted buyer email",
    timestamp: "2026-05-20T10:15:00",
    intentScore: 94,
    aiInterpretation: "Daniel is showing high buyer intent because he clicked the brochure twice and has viewed similar Folsom homes.",
    recommendedAction: "Draft private showing text."
  },
  {
    id: "DIS-1003",
    platform: "Google Search",
    city: "Folsom",
    visitorType: "Anonymous",
    activity: "Search traffic increased for 'Folsom homes under $950K'",
    frequency: 145,
    source: "Organic Search",
    timestamp: "2026-05-20T11:00:00",
    intentScore: 82,
    aiInterpretation: "This supports stronger buyer demand for Willow Crest Lane.",
    recommendedAction: "Build a Google-friendly listing description and targeted email campaign."
  },
  {
    id: "DIS-1004",
    platform: "Instagram",
    listingId: "L-104",
    address: "2457 Blackstone Drive",
    visitorType: "Anonymous",
    activity: "Backyard image drove highest engagement",
    frequency: 890,
    source: "Social Media Ads",
    timestamp: "2026-05-20T14:30:00",
    intentScore: 85,
    aiInterpretation: "Luxury lifestyle angle is working.",
    recommendedAction: "Create a short-form video campaign focused on outdoor entertaining."
  },
  {
    id: "DIS-1005",
    platform: "Open House QR",
    listingId: "L-105",
    address: "36 Clinton Avenue Unit 4D",
    visitorType: "Anonymous",
    activity: "Nine visitors scanned QR code, only three added to CRM",
    frequency: 9,
    source: "On-site Signage",
    timestamp: "2026-05-20T16:45:00",
    intentScore: 88,
    aiInterpretation: "Follow-up leakage risk.",
    recommendedAction: "Create missing contacts and rank attendees by intent."
  }
];
